Suppression thread lié message supprimé
TanguyChiffoleau/Le-bot-en-JS pull request #271
Opened 2022-02-23 14:24 UTC by Asthox

2022-02-24 21:52 UTC, TanguyChiffoleau commented
Je comprend pas le but de la PR

2022-02-24 21:56 UTC, Asthox commented
Quand on supprime un message dans les salons où se créent les threads auto, le thread associé reste. Du coup faut le supprimer en même temps

2022-02-24 22:00 UTC, TanguyChiffoleau commented
Car c'est le bot qui créer le thread c'est ça ?

2022-02-24 22:06 UTC, Asthox commented
yes

2022-02-25 16:29 UTC, TanguyChiffoleau commented
Ce serait bien de vérifier si le thread qui va être supprimé a été créé par le bot, sinon on risque de supprimer des threads qui ne sont pas liés au bot.
Je me demande si c'est pas mieux d'archiver le thread plutôt que de le supprimer directement (peut-être uniquement supprimer si le thread est vide)

2022-02-25 16:47 UTC, Asthox commented
Je sais pas, le soucis que je voyais est surtout les messages non autorisés dans ces salons, qui sont supprimés par des modos/certifs, mais du coup le thread reste
Le supprimer serait mieux, au moins on enlève vraiment publiquement la trace

2022-02-25 17:03 UTC, TanguyChiffoleau commented
Dans ce cas là les modos le supprimeront c'est pas un soucis, mais en l'état on supprime n'importe quel thread c'est pas possible. Il faudrait pouvoir check si le thread vient du bot

2022-02-25 17:21 UTC, Asthox commented
Dans ce cas le mieux est de vérifier plusieurs choses :
- si message supprimé est dans salon avec création de thread auto -> on supprime le thread associé
- si le message supprimé est dans un salon autre (entraide, etc.) -> on archive le thread associé
bon compromis ?

2022-03-01 17:49 UTC, TanguyChiffoleau requested changes
En plus des `await`, ce serait bien de vérifier si le thread a été créé par le bot (`<ThreadChannel>.ownerId`. On pourrait aussi vérifier si le thread est archivable par le bot (`<ThreadChannel>.unarchivable`) et si le message n'est pas déjà archivé avant de l'archiver (`<ThreadChannel>.archived`). Aussi, `<ThreadChannel>.messageCount` serait plus adapté que `<ThreadChannel>.messages.cache.size`.

2022-03-01 17:49 UTC, TanguyChiffoleau commented on src/events/logs/messageDelete.js
> +	else await message.thread.delete()
Je ne pense pas que les await soient utiles, on a pas besoin d'attendre la suppression du thread avant de pouvoir poursuivre pour log le message supprimé

2022-03-04 08:17 UTC, TanguyChiffoleau commented on src/events/logs/messageDelete.js
> +		else thread.delete()
Si le thread est archivé, qu'importe s'il est vide ou non il sera supprimé. Il faut ignorer si le thread est déjà archivé
```suggestion
		if (!thread.archived) {
				if (thread.messageCount > 1) thread.setArchived(true)
				else thread.delete()
		}
```

2022-03-06 16:57 UTC, TanguyChiffoleau approved these changes

2022-03-06 17:02 UTC, merged