Ancienne PR
TanguyChiffoleau/Le-bot-en-JS pull request #68
Opened 2020-12-29 18:41 UTC by Emilien212

2020-12-30 09:32 UTC, TanguyChiffoleau requested changes
- Des returns doivent être utilisés pour terminer le programme dès qu'il a éffectué une action, pour éviter qu'il fasse des actions supplémentaires non désirables

2020-12-30 09:44 UTC, TanguyChiffoleau requested changes
- Des returns doivent être utilisés pour terminer le programme dès qu'il a éffectué une action, pour éviter qu'il fasse des actions supplémentaires non désirables

2020-12-30 09:44 UTC, TanguyChiffoleau commented on src/events/client/voiceStateUpdate.js
> +		client.voiceManager.user_channel.push(channel.id)
```suggestion
		return client.voiceManager.user_channel.push(channel.id)
```

2020-12-30 09:44 UTC, TanguyChiffoleau commented on src/events/client/voiceStateUpdate.js
> +	}
```suggestion
		// Suppresion du no mic du channel
		if (oldState.channelID in client.voiceManager.no_mic)
			await client.voiceManager.no_mic[oldState.channelID].delete()

		// Suppression channel
		await client.channels.cache.get(oldState.channelID).delete()
		return client.voiceManager.user_channel.splice(
			client.voiceManager.user_channel.indexOf(oldState.channelID),
			1,
		)
	}
```

2020-12-30 09:44 UTC, TanguyChiffoleau commented on src/events/client/voiceStateUpdate.js
> +			.delete()
```suggestion
		// Supprime les permissions du membre pour le no mic
		return client.voiceManager.no_mic[oldState.channelID].permissionOverwrites
			.get(newState.id)
			.delete()
```

2020-12-30 09:44 UTC, TanguyChiffoleau commented on src/events/client/voiceStateUpdate.js
> +			})
```suggestion
		if (set_perm)
			return client.voiceManager.no_mic[newState.channelID].updateOverwrite(newState.id, {
				CREATE_INSTANT_INVITE: false,
				MANAGE_CHANNELS: false,
				MANAGE_ROLES: false,
				MANAGE_WEBHOOKS: false,
				VIEW_CHANNEL: true,
				SEND_MESSAGES: true,
				SEND_TTS_MESSAGES: false,
				MANAGE_MESSAGES: false,
				EMBED_LINKS: true,
				ATTACH_FILES: true,
				READ_MESSAGE_HISTORY: true,
				MENTION_EVERYONE: false,
				USE_EXTERNAL_EMOJIS: true,
				ADD_REACTIONS: true,
			})
```

2020-12-30 11:51 UTC, Emilien212 commented on src/events/client/voiceStateUpdate.js
> +		client.voiceManager.user_channel.push(channel.id)
> 

C'était fait exprès de ne pas mettre de return car si par exemple l'utilisateur qui son channnel perso et va dans le channel pour en crée un le bot doit faire 2 actions, supprimer l'ancien et en crée un nouveau du coup pas de return (ou alors j'ai mal compris ce que tu voulais faire).

2020-12-30 11:55 UTC, Emilien212 commented on src/events/client/voiceStateUpdate.js
> +			.delete()
> 

Je comprends pas l'utilisation du return ici, il ne dois pas arrêter le programme après ? Il doit encore setup toutes les perms

2020-12-30 11:55 UTC, Emilien212 commented on src/events/client/voiceStateUpdate.js
> +			})
Ici aussi, pourquoi un return ?

2020-12-30 11:59 UTC, Emilien212 commented on src/events/client/voiceStateUpdate.js
> +	}
> 

J'ai oublié de supprimé le channel no_mic de l'objet, tu sais ajouter à a ligne 29. "delete client.voiceManager.no_mic[oldState.channelID]"

2021-03-07 11:02 UTC, TanguyChiffoleau commented on src/commands/misc/nomic.js
> +	usage: null,
Usage à renseigner

2021-03-07 11:10 UTC, TanguyChiffoleau requested changes

2021-03-07 11:10 UTC, TanguyChiffoleau commented on src/commands/misc/nomic.js
> +			return message.reply(`il y a déjà un channel no-mic : ${existingNoMicChannel} 😕`)
Il faut ajouter un commentaire

2021-03-07 11:10 UTC, TanguyChiffoleau commented on src/commands/misc/nomic.js
> +	usage: null,
Usage à renseigner

2021-03-07 11:10 UTC, TanguyChiffoleau commented on src/commands/misc/nomic.js
> +			voiceChannel.name.replace("'s channel", ' no mic'),
Traduction en français ?

2021-03-07 11:10 UTC, TanguyChiffoleau commented on src/events/client/voiceStateUpdate.js
> +	}
Utiliser des fonctions pour traiter le cas où l'utilisateur quitte/rejoint un channel pour simplifier

2021-03-07 16:19 UTC, TanguyChiffoleau approved these changes
Tout me semble correct. La PR sera merge si il n'y a pas de modifications à faire après avoir fait béta-tester le système.

2021-03-07 18:11 UTC, TanguyChiffoleau requested changes
Les fichiers créés/modifiés ne respectent pas les modules ECMAScript instaurés dans https://github.com/TanguyChiffoleau/Le-bot-en-JS/pull/86.

2021-03-08 10:37 UTC, TanguyChiffoleau approved these changes
La PR me semble prête à être merge.

2021-03-08 15:15 UTC, merged